Fixed exception error
ERROR: When you add locomotive, add passenger, add freight, then remove
all 3 of them then add loco then add passenger carriage it errors:
Train Exception: Invalid train configuration. Cannot addCarriage() for
passengers to train after freight carriages have been added.

CAUSE: A tracker var was set when a freight carriage had been added, it
was never unset.

FIX: Removed the tracker var, replaced with checking the train
toString() to see if it contains a freight carriage.